# Generated by Django 3.2.8 on 2021-10-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamedwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Gamedwork',
        ),
    ]
